services:

  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: busybox:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - ./tempo-data:/var/tempo

  tempo:
    image: grafana/tempo:2.4.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/var/tempo
    ports:
      - "34268:14268" # jaeger ingest
      - "33200:3200"  # tempo search
      - "39095:9095"  # tempo grpc
      - "34317:4317"  # otlp grpc
      - "34318:4318"  # otlp http
      - "39411:9411"  # zipkin
    depends_on:
      - init

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "35672:5672"   # AMQP
      - "45672:15672"  # Management
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 5s
      timeout: 5s
      retries: 3

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "39090:9090"

  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - "33000:3000"

  producer:
    build:
      context: ./producer
    depends_on:
      rabbitmq:
        condition: service_healthy
      tempo:
        condition: service_started
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317 #    - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq/%2f
    ports:
      - "38000:8000"

  consumer:
    build:
      context: ./consumer
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
      tempo:
        condition: service_started
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317
      - PYTHONUNBUFFERED=1 #    - CLOUDAMQP_URL=amqp://guest:guest@rabbitmq/%2f

  next_api:
    build:
      context: ./next_api
    depends_on:
      rabbitmq:
        condition: service_healthy
      tempo:
        condition: service_started
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=tempo:4317
      - PYTHONUNBUFFERED=1
    ports:
      - "38001:8001"
